spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5

server:
  port: 9090
  
logging:
  level:
    org.springframework.security: 'DEBUG'
    com.nomadays.sso: 'DEBUG'
    com.nomadays.client1: 'DEBUG'