spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5

# Should be run the host different from localhost, so it doesn't share the cookie with login.
# Should configure that host in the login server's  `allowed-uris` in application.yml
server:
  port: 9090
  
logging:
  level:
    org.springframework.security: 'DEBUG'
    com.nomadays.sso: 'DEBUG'
    com.nomadays.client1: 'DEBUG'